service: employee-portal-service
provider:
  name: aws
  runtime: nodejs18.x
  stage: sit
  region: us-east-2
  environment:
    PG_HOST: database-1.crmqmwsmwk90.us-east-2.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: employee
    PG_USERNAME: postgres
    PG_PASSWORD: postgres

functions:
  employeeGet:
    handler: src/Lamda/employee/employeeCreateHandler.getEmployee
    timeout: 900
    memorySize: 128
    events:
      - http:
          path: employee
          method: GET
          cors: true
          request:
            parameters:
              querystrings:
                employeeId: true

plugins:
  - serverless-iam-roles-per-function