service: employee-portal-service
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    PG_HOST: 13.200.180.211
    PG_PORT: 5432
    PG_DATABASE: emp-dev
    PG_USERNAME: postgres
    PG_PASSWORD: postgres

functions:
  employeeGet:
    handler: src/Lamda/employee/employeeHandler.getEmployee
    timeout: 300
    memorySize: 128
    events:
      - http:
          path: employee
          method: GET
          cors: true
          request:
            parameters:
              querystrings:
                employeeId: true
  employeePost:
    handler: src/Lamda/employee/employeeHandler.createEmployee
    timeout: 120
    memorySize: 128
    events:
      - http:
          path: employee
          method: POST
          cors: true

plugins:
  - serverless-iam-roles-per-function