service: employee-portal-service
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    EMPLOYEE_TABLE: ${self:custom.employeeTableName}
custom:
  employeeTableName: employee-Details-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  employeeCreate:
    handler: src/Lamda/employee/employeeCreateHandler.createEmployee
    name: createemployee
    memorySize: 512
    timeout: 120
    events:
      - http:
          path: employee
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:UpdateItem"
          - "dynamodb:GetItem"
          - "dynamodb:Scan"
          - "dynamodb:DeleteItem"
        Resource:
          - !GetAtt EmployeeTable.Arn

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTable}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        