service: employee-portal-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    EMPLOYEE_TABLE: ${self:custom.employeeTableName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:GetItem"
        - "dynamodb:Scan"
        - "dynamodb:DeleteItem"
        # - "dynamodb:Query"
      Resource:
        - !GetAtt EmployeeTable.Arn
        # - !Sub "${EmployeeTable.Arn}/index/officeEmailAddress-index" # Add this line to allow Query on the index

custom:
  employeeTableName: employee-Details-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  employeeCreate:
    handler: src/Lamda/employee/employeeCreateHandler.createEmployee
    name: employeeCreate
    memorySize: 128
    timeout: 120
    events:
      - http:
          path: employee
          method: POST

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTableName}
        AttributeDefinitions:
          - AttributeName: employeeId
            AttributeType: S
          - AttributeName: createdDateTime
            AttributeType: S
        KeySchema:
          - AttributeName: employeeId
            KeyType: HASH
          - AttributeName: createdDateTime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
